process:
  id: process-23009
  name: Prozess 23009
  category: WiM
  version: '2.6'
  description: Beschreibung wird durch Willi Mako ergänzt.
  willi_mako_context:
    session_id: bda5ed94-2346-4c35-8ec7-9140ba674f0e
    knowledge_base_ids:
      - 2a283c53-d606-5b4a-b854-8ac0408339c9
      - 59853e3d-0cb1-56ba-971f-1ccc31619033
      - fe3cc5c5-a930-51e9-ba24-2d6a280c30ad
      - 93d46e4c-9944-59fb-a888-c11e8d21b9ea
      - 27900fe1-b4fa-5e1d-966f-9619bdd6cb87
      - cfcf0c04-8949-515e-88bb-54e31a8f2422
      - cb7f02de-e09f-5e3b-9a94-614f72480ffb
      - 4fb145b0-f3e9-580c-8fbe-91f06f2654f4
      - dce490a2-ee58-5cfc-9534-d2d032e46542
      - ef6caa3b-fdc2-59fe-ba57-0d19dc932432
    reasoning_quality: 1
    reasoning_iterations: 1
    reasoning_steps: 4
    search_query: Liste strukturierte Informationen zum Prüfidentifikator 23009 (wim).
    total_results: 10
    search_duration_ms: 1941
    response_format: text
    raw_response: >-
      Der Prüfidentifikator 23009 konnte in den bereitgestellten Kontextauszügen nicht gefunden werden. Die vorliegenden
      Informationen beziehen sich lediglich auf den Prüfidentifikator 13009.


      Bitte überprüfen Sie die Prüfidentifikator-Nummer, um eine präzise Definition zu erhalten.
    captured_at: '2025-10-21T12:17:35.139Z'
trigger:
  message_type: UTILMD
  pruefidentifikator: '23009'
  direction: bidirectional
  sender_role: UNBEKANNT
  receiver_role: UNBEKANNT
responses:
  - message_type: APERAK
    pruefidentifikator: '23009'
    direction: bidirectional
    description: Automatische Antwort für Prüfidentifikator 23009.
    max_wait_days: 3
    transitions_to: completed
states:
  pending:
    name: Ausstehend
    is_final: false
    expected_responses:
      - '23009'
  completed:
    name: Abgeschlossen
    is_final: true
    timeout_days: 0
    expected_responses: []
validations: []
documentation: {}
