process:
  id: '31003'
  name: WiM-Rechnung
  category: WiM
  version: '2.6'
  description: Abrechnung von Leistungen im Rahmen der Wechselprozesse im Messwesen (WiM).
  bdew_reference: Anwendungsübersicht der Prüfidentifikatoren
  willi_mako_context:
    session_id: bda5ed94-2346-4c35-8ec7-9140ba674f0e
    knowledge_base_ids:
      - 3e3ad5a1-1954-8b3f-e3ca-334de00a4bb5
      - 4a438346-dedd-1b8e-df6e-c471837c4f84
      - cd75153b-a434-5e1f-bff0-0e55854713a8
      - b4ffcf70-d6e7-51f3-a9c7-2dd1786ac262
      - 1a518998-0752-5c29-badf-d44f144ce389
      - e9925758-d907-51f0-b3ad-3443c4f78547
      - dbd1cbd8-608d-5003-b491-9beb2795ea12
      - 4dded481-5585-53e0-9068-30cce81a3082
      - 5e8f47e1-a55c-5203-a537-f660655ecba9
      - 90f6d24b-d155-5076-bfd6-995af161472a
    reasoning_quality: 1
    reasoning_iterations: 1
    reasoning_steps: 4
    search_query: Liste strukturierte Informationen zum Prüfidentifikator 31003 (wim).
    total_results: 10
    search_duration_ms: 1950
    response_format: json
    captured_at: '2025-10-21T12:20:14.477Z'
trigger:
  message_type: INVOIC
  pruefidentifikator: '31003'
  direction: outbound
  sender_role: TODO (Z.B. MSB, NB)
  receiver_role: TODO (Z.B. LF, NB)
responses:
  - message_type: APERAK
    pruefidentifikator: '00000'
    direction: outbound
    description: Bestätigung des Empfangs der WiM-Rechnung
    max_wait_days: 2
    transitions_to: completed
states:
  pending:
    name: Warten auf Bestätigung der WiM-Rechnung
    is_final: false
    timeout_days: 2
    expected_responses:
      - '00000'
  completed:
    name: WiM-Rechnungsprozess abgeschlossen
    is_final: true
    timeout_days: 0
    expected_responses: []
validations:
  - field: MarketLocationID
    rule: valid_mp_id
    message: Die Marktlokations-ID muss gültig sein.
    severity: error
  - field: InvoiceDate
    rule: exists
    message: Das Rechnungsdatum muss vorhanden sein.
    severity: error
  - field: TotalAmount
    rule: not_empty
    message: Der Rechnungsbetrag muss angegeben werden.
    severity: error
documentation: {}
