process:
  id: '31007'
  name: Aggregierte Mehr-/Mindermenge
  category: WiM
  version: '2.6'
  description: Abbildung der aggregierten Mehr-/Mindermengen von Netzbetreibern an Marktgebietsverantwortliche in der Sparte Gas.
  willi_mako_context:
    session_id: bda5ed94-2346-4c35-8ec7-9140ba674f0e
    knowledge_base_ids:
      - 3e3ad5a1-1954-8b3f-e3ca-334de00a4bb5
      - 4a438346-dedd-1b8e-df6e-c471837c4f84
      - b4ffcf70-d6e7-51f3-a9c7-2dd1786ac262
      - cd75153b-a434-5e1f-bff0-0e55854713a8
      - fe3cc5c5-a930-51e9-ba24-2d6a280c30ad
      - dce490a2-ee58-5cfc-9534-d2d032e46542
      - 4fb145b0-f3e9-580c-8fbe-91f06f2654f4
      - 93d46e4c-9944-59fb-a888-c11e8d21b9ea
      - 27900fe1-b4fa-5e1d-966f-9619bdd6cb87
      - 59853e3d-0cb1-56ba-971f-1ccc31619033
    reasoning_quality: 1
    reasoning_iterations: 1
    reasoning_steps: 4
    search_query: Liste strukturierte Informationen zum Prüfidentifikator 31007 (wim).
    total_results: 10
    search_duration_ms: 1782
    response_format: json
    captured_at: '2025-10-21T12:22:54.223Z'
trigger:
  message_type: INVOIC
  pruefidentifikator: '31007'
  direction: outbound
  sender_role: NB
  receiver_role: MGV
responses:
  - message_type: APERAK
    pruefidentifikator: '31007'
    direction: outbound
    description: Funktionale Bestätigung der aggregierten Mehr-/Mindermengen-Rechnung.
    max_wait_days: 2
    transitions_to: completed
states:
  pending:
    name: Warten auf funktionale Bestätigung
    is_final: false
    timeout_days: 3
    expected_responses:
      - '00000'
      - '31007'
  completed:
    name: Prozess abgeschlossen
    is_final: true
    timeout_days: 0
    expected_responses: []
validations:
  - field: pruefidentifikator
    rule: exists
    message: Der Prüfidentifikator 31007 muss vorhanden sein.
    severity: error
  - field: Nachrichtendatum
    rule: exists
    message: Das Nachrichtendatum muss vorhanden sein.
    severity: error
  - field: Netzbetreiber-ID
    rule: valid_mp_id
    message: Eine gültige Marktpartner-ID des Netzbetreibers ist erforderlich.
    severity: error
  - field: Marktgebietsverantwortlicher-ID
    rule: valid_mp_id
    message: Eine gültige Marktpartner-ID des Marktgebietsverantwortlichen ist erforderlich.
    severity: error
  - field: Sparte
    rule: exists
    message: Die Sparte muss 'Gas' sein.
    severity: error
documentation: {}
