process:
  id: '31010'
  name: Kapazitätsrechnung
  category: WiM
  version: '5.5'
  description: Prozess zur Abrechnung von Kapazitäten im Rahmen der Marktkommunikation.
  willi_mako_context:
    session_id: bda5ed94-2346-4c35-8ec7-9140ba674f0e
    knowledge_base_ids:
      - 3e3ad5a1-1954-8b3f-e3ca-334de00a4bb5
      - 4a438346-dedd-1b8e-df6e-c471837c4f84
      - b4ffcf70-d6e7-51f3-a9c7-2dd1786ac262
      - cd75153b-a434-5e1f-bff0-0e55854713a8
      - 5e8f47e1-a55c-5203-a537-f660655ecba9
      - 90f6d24b-d155-5076-bfd6-995af161472a
      - 3af396d2-55b8-5bb1-8f0a-ea0aa2185bf7
      - 9ccf1a7f-ac0d-5544-88cb-da90e741b82d
      - 4de6d2d0-6323-5915-8a73-9bf713c8a7e8
      - 41f3c119-47e6-5ec3-a4a8-72a69a49df94
    reasoning_quality: 1
    reasoning_iterations: 1
    reasoning_steps: 4
    search_query: Liste strukturierte Informationen zum Prüfidentifikator 31010 (wim).
    total_results: 10
    search_duration_ms: 1796
    response_format: json
    captured_at: '2025-10-21T12:24:14.477Z'
trigger:
  message_type: INVOIC
  pruefidentifikator: '31010'
  direction: outbound
  sender_role: 'TODO: NETZBETREIBER (NB)'
  receiver_role: 'TODO: LIEFERANT (LF) ODER WEITERER MARKTPARTNER'
responses:
  - message_type: APERAK
    pruefidentifikator: '00000'
    direction: outbound
    description: Rechnungsbestätigung oder Ablehnung der Kapazitätsrechnung.
    max_wait_days: 14
    transitions_to: completed
states:
  pending:
    name: Warten auf Rechnungsbestätigung
    is_final: false
    timeout_days: 14
    expected_responses:
      - '00000'
  completed:
    name: Rechnungsprozess abgeschlossen
    is_final: true
    timeout_days: 0
    expected_responses: []
validations:
  - field: reference_number
    rule: exists
    message: Referenznummer der Rechnung muss vorhanden sein.
    severity: error
  - field: amount
    rule: not_empty
    message: Rechnungsbetrag muss angegeben werden.
    severity: error
  - field: billing_period
    rule: exists
    message: Abrechnungsperiode muss vorhanden sein.
    severity: error
  - field: invoice_date
    rule: future_date
    message: Rechnungsdatum sollte kein zukünftiges Datum sein.
    severity: warning
documentation: {}
