process:
  id: gpke-a011
  name: Prozessdefinition für GPKE_A011
  category: GPKE
  version: UNKNOWN
  description: Die spezifischen Details für diesen Prüfidentifikator sind im vorliegenden Kontext nicht definiert.
  willi_mako_context:
    session_id: 983f944d-d83b-49bd-8830-160c2865d184
    knowledge_base_ids:
      - 06195ed6-691d-57c3-a2f6-4ebfa96443dc
      - 8ae7b6e0-eda3-5128-80ab-415d67aeb5e1
      - f7cff05f-f51d-563c-a429-700189a8220b
      - 98b68fa5-f15e-5585-85c4-668153925057
      - c4fa97b9-c637-5c26-ac21-39517ef1c7f1
      - 4cb80e3a-3a17-5d30-88a6-523ced68f788
      - 3c347616-5607-5659-9297-e42c1cf58bb6
      - 40df8e02-b680-54ef-ab80-726db315d422
      - bfc0f729-6c64-589c-b277-7771b9013fd0
      - ef889753-c7b3-54fb-90ed-23473f2b5123
    reasoning_quality: 1
    reasoning_iterations: 1
    reasoning_steps: 4
    search_query: Liste strukturierte Informationen zum Prüfidentifikator GPKE_A011 (gpke).
    total_results: 10
    search_duration_ms: 2121
    response_format: json
    captured_at: '2025-10-21T08:43:35.347Z'
trigger:
  message_type: UTILMD
  pruefidentifikator: '00011'
  direction: bidirectional
  sender_role: UNKNOWN
  receiver_role: UNKNOWN
responses:
  - message_type: APERAK
    pruefidentifikator: '00011'
    direction: bidirectional
    description: Automatische Antwort für Prüfidentifikator 00011.
    max_wait_days: 3
    transitions_to: completed
states:
  pending:
    name: Ausstehend
    is_final: false
    expected_responses:
      - '00011'
  completed:
    name: Abgeschlossen
    is_final: true
    expected_responses: []
    timeout_days: 0
validations: []
documentation: {}
