process:
  id: '55644'
  name: 'TODO: Prozessname für Prüfidentifikator 55644 (GPKE)'
  category: GPKE
  version: '2.6'
  description: >-
    Definition des Geschäftsprozesses, der durch den Prüfidentifikator 55644 im Rahmen der GPKE abgebildet wird. Details
    zum Anwendungsfall sind aktuell nicht in der Wissensbasis verfügbar.
  willi_mako_context:
    session_id: bda5ed94-2346-4c35-8ec7-9140ba674f0e
    knowledge_base_ids:
      - c11936e9-1b63-46c8-a628-2966d9ef9d49
      - b5441735-258f-5070-9bda-1b2d2de3411e
      - 4dd24e49-4bc1-5381-a241-fe70137cce25
      - b15eb7ec-a2eb-4740-9e45-e7a6e82ad66c
      - e535d28b-b6af-fa6a-e075-1f99ad3147e3
      - 69335d35-9c5e-4a46-bc6b-091865f196c9
      - f27ec4d5-359c-5439-bd42-2cd8115e5e48
      - ff90d232-d4f1-57fa-b4ab-8410536c7543
      - b0e41e96-1aa2-4299-ad2a-81700d1bb6f7
      - a49efe0a-2d89-48b2-97d0-47899462e634
    reasoning_quality: 1
    reasoning_iterations: 1
    reasoning_steps: 4
    search_query: Liste strukturierte Informationen zum Prüfidentifikator 55644 (gpke).
    total_results: 10
    search_duration_ms: 1830
    response_format: json
    captured_at: '2025-10-21T12:06:57.470Z'
trigger:
  message_type: UTILMD
  pruefidentifikator: '55644'
  direction: bidirectional
  sender_role: 'TODO: SENDERROLLE'
  receiver_role: 'TODO: EMPFÄNGERROLLE'
responses:
  - message_type: APERAK
    pruefidentifikator: '00000'
    direction: bidirectional
    description: Empfangsbestätigung oder Fehlermeldung für die ausgelöste Nachricht.
    max_wait_days: 3
    transitions_to: completed
states:
  pending:
    name: Warten auf Bestätigung
    is_final: false
    timeout_days: 5
    expected_responses:
      - '00000'
  completed:
    name: Abgeschlossen
    is_final: true
    timeout_days: 0
    expected_responses: []
validations: []
documentation: {}
